# Data Cleaning

**NAME:** Jake Rood

**LAST UPDATE:** 07-14-2024

In this notebook the data is cleaned by merging the two data sources, creating a new feature (HR%), cleaning up the columns and, filtering only to include batters who have met the plate appearances threshold.

## IMPORTS

In [1]:
# Import pandas
import pandas as pd

# Set the display precision to four decimal places
pd.set_option("display.precision", 4)

# Load the bat tracking metrics and batting statistics into dataframes
tracking = pd.read_csv('bat-tracking.csv')
stats = pd.read_csv('batting-statistics.csv')

## VIEW

In [2]:
# View the head of the tracking df
tracking.head()

,id,name,swings_competitive,percent_swings_competitive,contact,avg_bat_speed,hard_swing_rate,squared_up_per_bat_contact,squared_up_per_swing,blast_per_bat_contact,blast_per_swing,swing_length,swords,batter_run_value,whiffs,whiff_per_swing,batted_ball_events,batted_ball_event_per_swing
0,519317,"Stanton, Giancarlo",424,0.9158,294,80.7386,0.9811,0.2993,0.2075,0.2721,0.1887,8.3993,4,5.3460,130,0.3066,151,0.3561
1,670242,"Wallner, Matt",32,0.8889,18,78.4095,0.9062,0.1111,0.0625,0.1111,0.0625,7.3262,1,0.5991,14,0.4375,6,0.1875
2,678877,"Noel, Jhonkensy",30,0.9091,23,78.1815,0.7667,0.1739,0.1333,0.1304,0.1000,7.9588,0,1.5225,7,0.2333,6,0.2000
3,665833,"Cruz, Oneil",400,0.9112,275,78.1058,0.7475,0.3309,0.2275,0.2255,0.1550,7.6466,3,-10.8187,125,0.3125,136,0.3400
4,672744,"Canario, Alexander",36,0.9000,21,77.5654,0.8056,0.2381,0.1389,0.0952,0.0556,8.0235,2,-0.6171,15,0.4167,10,0.2778

In [3]:
# View the head of the stats df
stats.head()

,Name,Team,PA,AB,H,1B,2B,3B,HR,R,...,SLG,OPS,wOBA,wRC+,EV,Barrel%,HardHit%,NameASCII,PlayerId,MLBAMID
0,Ben Gamel,NYM,2,1,0,0,0,0,0,1,...,0.0000,0.5000,0.3455,129.2337,102.4379,0.0000,1.0000,Ben Gamel,12160,592325
1,Brian Anderson,ATL,5,5,0,0,0,0,0,0,...,0.0000,0.0000,0.0000,-100.0000,101.5561,0.3333,1.0000,Brian Anderson,18289,605119
2,José Tena,CLE,3,3,0,0,0,0,0,0,...,0.0000,0.0000,0.0000,-100.0000,99.6172,0.0000,1.0000,Jose Tena,23691,677588
3,Greg Jones,COL,6,5,1,0,0,0,1,1,...,0.8000,1.1333,0.4595,187.2449,109.6814,1.0000,1.0000,Greg Jones,25448,675659
4,James Wood,WSN,9,7,1,1,0,0,0,0,...,0.1429,0.4762,0.2520,60.3673,99.5747,0.0000,0.8333,James Wood,29518,695578

In [4]:
# Check how many columns are in the tracking df
len(tracking)

562

In [5]:
# Check how many columns are in the stats df
len(stats)

564

## MERGE

In [6]:
# Merge the tracking df and stats df on "id" and "MLBAMID"
merged = tracking.merge(stats, left_on="id", right_on="MLBAMID")

In [7]:
# View the merged df
merged.head()

,id,name,swings_competitive,percent_swings_competitive,contact,avg_bat_speed,hard_swing_rate,squared_up_per_bat_contact,squared_up_per_swing,blast_per_bat_contact,...,SLG,OPS,wOBA,wRC+,EV,Barrel%,HardHit%,NameASCII,PlayerId,MLBAMID
0,519317,"Stanton, Giancarlo",424,0.9158,294,80.7386,0.9811,0.2993,0.2075,0.2721,...,0.4923,0.7948,0.3425,124.8744,94.3319,0.1941,0.5412,Giancarlo Stanton,4949,519317
1,670242,"Wallner, Matt",32,0.8889,18,78.4095,0.9062,0.1111,0.0625,0.1111,...,0.2400,0.5127,0.2512,61.6037,86.1040,0.1111,0.3333,Matt Wallner,26466,670242
2,678877,"Noel, Jhonkensy",30,0.9091,23,78.1815,0.7667,0.1739,0.1333,0.1304,...,0.7692,1.0549,0.4347,188.0981,96.8194,0.3333,0.5000,Jhonkensy Noel,24257,678877
3,665833,"Cruz, Oneil",400,0.9112,275,78.1058,0.7475,0.3309,0.2275,0.2255,...,0.4240,0.7172,0.3082,97.6973,95.0281,0.1739,0.5272,Oneil Cruz,21711,665833
4,672744,"Canario, Alexander",36,0.9000,21,77.5654,0.8056,0.2381,0.1389,0.0952,...,0.4545,0.8145,0.3590,134.7780,83.1824,0.0909,0.2727,Alexander Canario,22842,672744

In [8]:
# Check how many columns are in the merged df
len(merged)

562

# FEATURE GENERATION
Statistics expressed as rates/percentages (AVG, SLG, K%, etc.) are more useful for our analysis. We want to create a new feature to express home runs as a percentage. We will take HR divided by AB to get the percent of at bats a batter hits a home run.

In [9]:
# Create a new column called "HR%"
merged['HR%'] = merged['HR'] / merged['AB']

## CLEAN COLUMNS

In [10]:
# Print a list of all columns in the merged df
print(merged.columns.tolist())

['id', 'name', 'swings_competitive', 'percent_swings_competitive', 'contact', 'avg_bat_speed', 'hard_swing_rate', 'squared_up_per_bat_contact', 'squared_up_per_swing', 'blast_per_bat_contact', 'blast_per_swing', 'swing_length', 'swords', 'batter_run_value', 'whiffs', 'whiff_per_swing', 'batted_ball_events', 'batted_ball_event_per_swing', 'Name', 'Team', 'PA', 'AB', 'H', '1B', '2B', '3B', 'HR', 'R', 'RBI', 'BB', 'IBB', 'SO', 'HBP', 'AVG', 'BB%', 'K%', 'OBP', 'SLG', 'OPS', 'wOBA', 'wRC+', 'EV', 'Barrel%', 'HardHit%', 'NameASCII', 'PlayerId', 'MLBAMID', 'HR%']

In [11]:
# Clean up the df by reordering columns and removing redundant/unnecessary columns
# This will help make our final data easier to read
cleaned_columns = [
    'id', 'Name', 'Team', 'swings_competitive', 'avg_bat_speed', 'swing_length', 'hard_swing_rate', 'squared_up_per_swing',
    'blast_per_swing', 'whiff_per_swing', 'PA', 'AB', 'AVG', 'SLG', 'HR%', 'BB%', 'K%', 'wRC+', 'EV', 'Barrel%', 'HardHit%'
]

# Create a new df using the cleaning columns
merged_cleaned = merged[cleaned_columns]

# View the cleaned df
merged_cleaned.head()

,id,Name,Team,swings_competitive,avg_bat_speed,swing_length,hard_swing_rate,squared_up_per_swing,blast_per_swing,whiff_per_swing,...,AB,AVG,SLG,HR%,BB%,K%,wRC+,EV,Barrel%,HardHit%
0,519317,Giancarlo Stanton,NYY,424,80.7386,8.3993,0.9811,0.2075,0.1887,0.3066,...,260,0.2462,0.4923,0.0692,0.0712,0.3203,124.8744,94.3319,0.1941,0.5412
1,670242,Matt Wallner,MIN,32,78.4095,7.3262,0.9062,0.0625,0.0625,0.4375,...,25,0.0800,0.2400,0.0400,0.0909,0.5152,61.6037,86.1040,0.1111,0.3333
2,678877,Jhonkensy Noel,CLE,30,78.1815,7.9588,0.7667,0.1333,0.1000,0.2333,...,13,0.2308,0.7692,0.1538,0.0714,0.5000,188.0981,96.8194,0.3333,0.5000
3,665833,Oneil Cruz,PIT,400,78.1058,7.6466,0.7475,0.2275,0.1550,0.3125,...,283,0.2367,0.4240,0.0424,0.0749,0.3257,97.6973,95.0281,0.1739,0.5272
4,672744,Alexander Canario,CHC,36,77.5654,8.0235,0.8056,0.1389,0.0556,0.4167,...,22,0.2727,0.4545,0.0455,0.0800,0.4400,134.7780,83.1824,0.0909,0.2727

## FILTER

In [12]:
# Filter the dataframe so we only include batters with at least 170 plate appearances
# This is to minimize the randomness caused by small sample sizes
# 170 was selected as the threshold because the average MLB team has played 85 games so far
# We want batters who average at least 2 plate appearances per game
# NOTE: MLB considers qualified batters for league leaders as batters with 3.1 PA per game
# The threshold was lowered to 2 PA per game for our purposes so we have a little more data to work with
merged_final = merged_cleaned[merged_cleaned['PA'] >= 170]

In [13]:
# View the final dataframe
merged_final.head()

,id,Name,Team,swings_competitive,avg_bat_speed,swing_length,hard_swing_rate,squared_up_per_swing,blast_per_swing,whiff_per_swing,...,AB,AVG,SLG,HR%,BB%,K%,wRC+,EV,Barrel%,HardHit%
0,519317,Giancarlo Stanton,NYY,424,80.7386,8.3993,0.9811,0.2075,0.1887,0.3066,...,260,0.2462,0.4923,0.0692,0.0712,0.3203,124.8744,94.3319,0.1941,0.5412
3,665833,Oneil Cruz,PIT,400,78.1058,7.6466,0.7475,0.2275,0.1550,0.3125,...,283,0.2367,0.4240,0.0424,0.0749,0.3257,97.6973,95.0281,0.1739,0.5272
6,656941,Kyle Schwarber,PHI,468,77.1365,7.8205,0.7500,0.2372,0.1581,0.3013,...,300,0.2500,0.4467,0.0567,0.1608,0.2807,133.3064,93.2535,0.1139,0.5396
8,592450,Aaron Judge,NYY,521,76.8650,8.1918,0.7313,0.2572,0.1996,0.3052,...,305,0.3213,0.7180,0.1049,0.1631,0.2487,217.9908,97.0803,0.2884,0.6279
9,656305,Matt Chapman,SFG,523,76.7800,7.4097,0.6711,0.1912,0.1281,0.2390,...,319,0.2382,0.4075,0.0345,0.0978,0.2374,109.5478,92.3920,0.1191,0.4766

In [14]:
# Check how many columns are in the final dataframe
len(merged_final)

269

## SAVE

In [15]:
# Save the final dataframe to a CSV file
merged_final.to_csv('final-data.csv', index=False)